[theme]
primaryColor = "#2E4A7D" # Azul da logo
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2f6"
textColor = "#1A3A5A"
font = "sans serif"

[browser]
gatherUsageStats = false
toolbarMode = "minimal"
